# -*- coding: utf-8 -*-
"""BCG X DS - feature_engineering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hXRlra5V_htdK8I3nqhkxE6jT_QQUCfJ
"""

import pandas as pd

# Load datasets
data_df = pd.read_csv('clean_data_after_eda.csv')
data_df["date_activ"] = pd.to_datetime(data_df["date_activ"], format='%Y-%m-%d')
data_df["date_end"] = pd.to_datetime(data_df["date_end"], format='%Y-%m-%d')
data_df["date_modif_prod"] = pd.to_datetime(data_df["date_modif_prod"], format='%Y-%m-%d')
data_df["date_renewal"] = pd.to_datetime(data_df["date_renewal"], format='%Y-%m-%d')

price_df = pd.read_csv('price_data.csv')
price_df["price_date"] = pd.to_datetime(price_df["price_date"], format='%Y-%m-%d')

# Remove irrelevant columns
data_df = data_df.drop(columns=['Unnamed: 0'], errors='ignore')
price_df = price_df.drop(columns=['Unnamed: 0'], errors='ignore')

# Extract new temporal features
price_df['year'] = price_df['price_date'].dt.year
price_df['month'] = price_df['price_date'].dt.month
price_df['day_of_week'] = price_df['price_date'].dt.dayofweek

# Calculate durations
data_df['duration_activ_to_end'] = (data_df['date_end'] - data_df['date_activ']).dt.days
data_df['days_to_renewal'] = (data_df['date_renewal'] - pd.Timestamp.now()).dt.days

# Combine columns to create derived features
price_df['price_var_ratio'] = price_df['price_off_peak_var'] / (price_df['price_peak_var'] + 1e-6)
price_df['price_change_percent'] = price_df.groupby('id')['price_off_peak_var'].pct_change()

# Merge datasets
merged_df = pd.merge(data_df, price_df, on='id', how='inner')

# Feature engineering on merged dataset
merged_df['avg_price'] = (merged_df['price_off_peak_var'] + merged_df['price_peak_var'] + merged_df['price_mid_peak_var']) / 3
merged_df['price_category'] = pd.cut(
    merged_df['avg_price'], bins=[0, 0.1, 0.2, float('inf')], labels=['Low', 'Medium', 'High']
)

# Save the transformed dataset
merged_df.to_csv('engineered_features.csv', index=False)

print("Feature engineering completed and saved to 'engineered_features.csv'.")